### PR TITLE
Fixed #145

### LINKED ISSUE #145: Connecting to a nebula managr hosted at a non root path
## Expected/Wanted Behavior
I had to host my manager at a non root path e.g. https://example.com/manager but the worker configuration does not allow for providing the path.

## Actual Behavior
Providing envvar `NEBULA_MANAGER_HOST="example.com/manager"` does not work as the manager URI is constructed inside the worker as: `protocol + "://" + host + ":" + str(port)`

## A possible suggestion
Add support for another env var NEBULA_MANAGER_URI and corresponding config var nebula_manager_uri using which user can provide the full URI (including protocol, host, port and any optional path) of manager e.g. `NEBULA_MANAGER_URI="https://example.com:8080/manager"`

If provided, URI should be used as it is, else constructed as being done currently.

If this suggestion sounds good, I can create a patch and raise PR.

### PR DESCRIPTION
**Pull request by vineyyadav**
Fixes #

Also swapped a couple of lines in Dockerfile for faster rebuilds.

## Proposed Changes

  -
  -
  -

### CODE REVIEW

**Review by naorlivne — CHANGES_REQUESTED** [review]
This will have to wait until the SDK is relesed with a new version that includes  before marging as the SDK version is currently version locked at `NebulaPythonSDK==2.7.0` in the worker which lacks the `host_uri` param and will thus break everything without this PR also updating the `NebulaPythonSDK` version

**Comment by vineyyadav** [comment]
> 
> This will have to wait until the SDK is relesed with a new version that includes [nebula-orchestrator/nebula-python-sdk#87](https://github.com/nebula-orchestrator/nebula-python-sdk/pull/87) before marging as the SDK version is currently version locked at `NebulaPythonSDK==2.7.0` in the worker which lacks the `host_uri` param and will thus break everything without this PR also updating the `NebulaPythonSDK` version

Sure. Let me know once the newer version of the SDK is published and I would push the change with bumped up version in requirements.txt

**Comment by naorlivne** [comment]
SDK version 2.8.0 released with your PR in it

**Review by naorlivne — APPROVED** [review]
LGTM

**Pull request merged**
